name: chatbotapp
description: A Flutter chat bot application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  timeago: ^3.2.2
  chat_bubbles: ^1.5.0
  uuid: ^4.3.3
  http: ^1.2.1
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/screenshots/
